# Generated by Django 2.1.7 on 2019-04-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_name', models.CharField(max_length=100)),
                ('youtube_id', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_upload_list_id', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_suscribers', models.IntegerField(default=0)),
                ('youtube_total_views', models.IntegerField(default=0)),
                ('youtube_total_videos', models.IntegerField(default=0)),
                ('twitter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('twitch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('streamer_thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('streamer_banner', models.CharField(blank=True, max_length=255, null=True)),
                ('streamer_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.Game')),
            ],
        ),
    ]
