# Generated by Django 2.1.7 on 2019-04-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0002_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='twitter_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streamer',
            name='twitter_followings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streamer',
            name='youtube_channel_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
