# Generated by Django 2.1.7 on 2019-04-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0003_auto_20190406_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='twitch_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
