# Generated by Django 2.1.7 on 2019-04-08 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0005_streamer_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('video_title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_description', models.TextField(blank=True, null=True)),
                ('video_thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('likeCount', models.IntegerField(default=0)),
                ('dislikeCount', models.IntegerField(default=0)),
                ('favoriteCount', models.IntegerField(default=0)),
                ('commentCount', models.IntegerField(default=0)),
                ('youtube_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.Game')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.Streamer')),
            ],
        ),
    ]
