# Generated by Django 2.1.7 on 2019-04-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0006_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
