# Generated by Django 2.1.7 on 2019-04-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0007_youtube_video_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='will_update_popular_video',
            field=models.BooleanField(default=True),
        ),
    ]
