# Generated by Django 2.1.7 on 2019-04-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0008_streamer_will_update_popular_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer_history',
            name='youtube_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='youtube_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='youtube_video_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
