# Generated by Django 2.1.7 on 2019-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0010_youtube_video_youtube_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video',
            name='embeddable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='youtube_video',
            name='license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtube_video',
            name='privacyStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtube_video',
            name='publicStatsViewable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='youtube_video',
            name='uploadStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
