# Generated by Django 2.1.7 on 2019-04-11 18:54
# This migration will be failed if you already added the record to streamer table. Please run sql manuary for 'foreign key to Gendar' then, run migrate fake. 


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0011_auto_20190410_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='streamer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamer',
            name='last_youtube_uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtube_video',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streamer',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streamer.Gender'),
        ),
    ]
