# Generated by Django 2.1.7 on 2019-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0012_auto_20190411_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video',
            name='is_category_set',
            field=models.BooleanField(default=False),
        ),
    ]
