# Generated by Django 2.1.7 on 2019-04-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0014_auto_20190411_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
