# Generated by Django 2.1.7 on 2019-04-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0015_streamer_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube_video',
            old_name='is_update',
            new_name='will_info_update',
        ),
    ]
