# Generated by Django 2.1.7 on 2019-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0016_auto_20190412_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_video',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
