# Generated by Django 2.1.7 on 2019-04-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0017_auto_20190412_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='is_information_update',
            new_name='is_ready',
        ),
        migrations.RenameField(
            model_name='youtube_video',
            old_name='is_category_set',
            new_name='is_ready',
        ),
    ]
