# Generated by Django 2.1.7 on 2019-04-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0018_auto_20190412_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='youtube_total_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streamer_history',
            name='youtube_total_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtube_video',
            name='viewCount',
            field=models.BigIntegerField(default=0),
        ),
    ]
