# Generated by Django 2.1.7 on 2019-04-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0019_auto_20190412_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_thumbnail',
        ),
        migrations.AddField(
            model_name='game',
            name='game_category',
            field=models.SmallIntegerField(choices=[(1, 'PC'), (2, 'Mobile'), (3, 'Console'), (4, 'Other')], default=4),
        ),
    ]
