# Generated by Django 2.1.7 on 2019-04-12 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0020_auto_20190412_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_tag_relation',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game_tag_relation',
            name='game_tag',
        ),
        migrations.AddField(
            model_name='game_tag',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streamer.Game'),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1),
        ),
        migrations.DeleteModel(
            name='Game_Tag_Relation',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
