# Generated by Django 2.1.7 on 2019-04-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0023_game_game_name_jp'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
