# Generated by Django 2.1.7 on 2019-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0024_game_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_tag',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
