# Generated by Django 2.1.7 on 2019-04-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0026_game_game_name_sys'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_tag',
            name='priority',
            field=models.SmallIntegerField(default=9),
        ),
    ]
