# Generated by Django 2.1.7 on 2019-04-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0027_game_tag_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewCount', models.BigIntegerField(default=0)),
                ('likeCount', models.IntegerField(default=0)),
                ('dislikeCount', models.IntegerField(default=0)),
                ('favoriteCount', models.IntegerField(default=0)),
                ('commentCount', models.IntegerField(default=0)),
                ('youtube_created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streamer.Game')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streamer.Streamer')),
                ('youtube_video_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='streamer.Youtube_Video')),
            ],
        ),
        migrations.AlterField(
            model_name='game_tag',
            name='priority',
            field=models.SmallIntegerField(choices=[(3, '3 : High'), (5, '5 : Middle'), (7, '7 : Low')], default=5),
        ),
    ]
