# Generated by Django 2.1.7 on 2019-04-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0029_auto_20190414_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube_video',
            old_name='video_thumbnail',
            new_name='video_thumbnail_medium',
        ),
        migrations.AddField(
            model_name='youtube_video',
            name='video_thumbnail_default',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
