# Generated by Django 2.1.7 on 2019-04-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0030_auto_20190416_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
