# Generated by Django 2.1.7 on 2019-04-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0031_youtube_video_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_video',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
