# Generated by Django 2.1.7 on 2019-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0032_auto_20190418_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to='streamer'),
        ),
    ]
