# Generated by Django 2.1.7 on 2019-05-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0034_game_game_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='youtube_id',
            new_name='youtube_channel_id',
        ),
        migrations.RenameField(
            model_name='streamer_history',
            old_name='youtube_id',
            new_name='youtube_channel_id',
        ),
        migrations.RenameField(
            model_name='youtube_video',
            old_name='youtube_id',
            new_name='youtube_channel_id',
        ),
    ]
