# Generated by Django 2.1.7 on 2019-05-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0035_auto_20190510_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube_video',
            old_name='youtube_video_id',
            new_name='youtube_video_org_id',
        ),
    ]
