# Generated by Django 2.1.7 on 2019-05-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0037_youtube_video_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video_rank',
            name='game_category',
            field=models.SmallIntegerField(choices=[(1, 'PC'), (2, 'Mobile'), (3, 'Console'), (4, 'Other')], default=4),
        ),
        migrations.AddField(
            model_name='youtube_video_rank',
            name='is_video_title_present',
            field=models.BooleanField(default=False),
        ),
    ]
