# Generated by Django 2.1.7 on 2019-05-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0042_auto_20190513_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video',
            name='is_low_views',
            field=models.BooleanField(default=False),
        ),
    ]
