# Generated by Django 2.1.7 on 2019-06-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0043_youtube_video_is_low_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video_rank',
            name='streamer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youtube_video_rank',
            name='streamer_thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtube_video_rank_tmp',
            name='streamer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youtube_video_rank_tmp',
            name='streamer_thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
