# Generated by Django 2.1.7 on 2019-06-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0045_auto_20190603_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_name_sys',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
