# Generated by Django 2.1.7 on 2019-06-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0046_auto_20190611_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_video_rank',
            name='game_name_sys',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youtube_video_rank_tmp',
            name='game_name_sys',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
