# Generated by Django 2.1.7 on 2019-06-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0048_twitter_post_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_post_history',
            name='url',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
