# Generated by Django 2.1.7 on 2019-07-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0049_auto_20190623_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjecdt', models.CharField(blank=True, max_length=255, null=True)),
                ('log_history', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
