# Generated by Django 2.1.7 on 2019-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0050_log_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='streamer',
            name='twitch_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
