# Generated by Django 2.1.7 on 2019-07-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0051_auto_20190720_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='twitch_id',
        ),
    ]
