# Generated by Django 2.1.7 on 2019-07-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0052_remove_streamer_twitch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamer',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
